services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    #image: n8nio/n8n:1.71.3
    restart: always
    #container_name: n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      #- N8N_EDITOR_BASE_URL=${EXTERNAL_IP}
      - WEBHOOK_URL=${EXTERNAL_IP}
    ports:
      - "5678:5678"
    networks:
      - n8n-network
    volumes:
      - ./vol_n8n:/home/node/.n8n
      #- n8n_data:/home/node/.n8n

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    networks:
      - n8n-network
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml

volumes:
  n8n_data:

networks:
  n8n-network:
    driver: bridge
